### ISSUE TITLE
Unknown attribute error

### ISSUE THREAD

**Issue by SM2DevLLC** [jasl/activeentity#8]
I'm getting `ActiveModel::UnknownAttributeError` in rails 6.1.1

**Comment by jasl** [comment]
> I'm getting `ActiveModel::UnknownAttributeError` in rails 6.1.1

Can you give me a sample? I'll check this weekend

**Comment by SM2DevLLC** [comment]
Sure thing. It seems to be specifically with calling `new` with an attribute. For example `MyModel.new(name: 'Test')`. I'll throw together a sample today.

**Comment by SM2DevLLC** [comment]
So after playing with it more, it does work, unless you try and pass `id`. For example if you pass `MyModel.new(id: 1)` it throws the error.

**Comment by jasl** [comment]
> So after playing with it more, it does work, unless you try and pass `id`. For example if you pass `MyModel.new(id: 1)` it throws the error.

Got it, thank you for report, I'll take a took

**Comment by SM2DevLLC** [comment]
Made a quick sample project showing the issue:

https://github.com/SM2DevLLC/ActiveEntityIssue

**Comment by SM2DevLLC** [comment]
We are using this in our app and are unable to push changes live until this is fixed or we'll need to use a different plugin/method. We'd be willing to pay you for your time if you could possibly fix this today.

**Comment by jasl** [comment]
> We are using this in our app and are unable to push changes live until this is fixed or we'll need to use a different plugin/method. We'd be willing to pay you for your time if you could possibly fix this today.

Will do now, sorry for delay

**Comment by jasl** [comment]
@SM2DevLLC Fixed, and released 6.1.1, please try

**Comment by SM2DevLLC** [comment]
Perfect. Thanks! Any way we can throw you some money as a thank you or at least get you a coffee?

**Comment by jasl** [comment]
> Perfect. Thanks! Any way we can throw you some money as a thank you or at least get you a coffee?

haha, you don't need to do this, enjoy my work & make a fortune.
